name: main workflow

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    name: Build, Test and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v2

      - name: Test
        working-directory: .
        run: cargo test
